%
clear
close
clc
expName = 'Area vs E overlay';
dataPath = {"E:\ µ—È “\E3_(rough)_CV_5mVps.txt"};
nFiles = length(dataPath);
potential = cell([nFiles 1]);
area = cell([nFiles 1]);

for i = 1:nFiles
    [potential{i},area{i}] = readData( dataPath{i},[1,2]);
    %area{i} = normalize(area{i}, 'range', [0 1]);
end

[fig, ax] = plotXY(potential{1}, area{1}, ...
    'XLabel', '{\itE} (V vs. Ag/AgCl)', ...
    'YLabel', '{\itA}_{592}', ...
    'YLim', [], ...
    'AspectRatio', 1.2, ...
    'FigureName', 'area_vs_pot', ...
    'PlotWidth', 5,...
    'Title','Area vs E overlay',...
    'TitleFontName', 'Arial');
if nFiles > 1
    for j = 2:nFiles
    plotXY(potential{j}, area{j}, ...
        'Color', j, ...
        'Axes', ax);
    end
end

legend(ax, ...
    {'25 °„C'; '30 °„C'; '35 °„C'}, ...
    'Location', 'best');

